on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  issue_comment:
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: qodo-ai/pr-agent@main
        env:
          CONFIG.MODEL: "gemini/gemini-2.5-flash-preview-05-20"
          GOOGLE_AI_STUDIO.GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG.CUSTOM_MODEL_MAX_TOKENS: 64000
          PR_REVIEWER.EXTRA_INSTRUCTIONS: 'タイトルと説明には日本語と英語でそれぞれ書いてください。'
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: 'タイトルと説明には日本語と英語でそれぞれ書いてください。 Titles should have prefix of commitlint pattern such as `feat:`, `chore:`, `test:`, `fix:`, `ci:`, `docs:` etc'
